export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILED = 'GET_POPULAR_MOVIES_FAILED';

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILED = 'GET_MOVIE_DETAILS_FAILED';

export const GET_LATEST_MOVIE = 'GET_LATEST_MOVIE';
export const GET_LATEST_MOVIE_SUCCESS = 'GET_LATEST_MOVIE_SUCCESS';
export const GET_LATEST_MOVIE_FAILED = 'GET_LATEST_MOVIE_FAILED';

export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILED = 'GET_GENRES_FAILED';

export const SET_LOADER = 'SET_LOADER';
